BO:
  method: evidence
  evidence:
    max_steps: 200
    acq_goal: 1e-1
    precision_goal: 0.01
    feedback_lvl: 1
    init_strat: Sobol
    ninit: 16
    gpfit_step: 1
    save: False
    save_file: 'test'
    save_step: 5
    ns_step: 10
    save_plot: True
    show_plot: False
    seed: 0
GP:
  method: fullybayesian
  fullybayesian:
    warmup_steps: 512
    num_samples: 512
    thinning: 16
    vmap_size: 8
    standardise_y: True
    noise: 1e-8
    kernel: rbf
    min_lengthscale: 1.e-3
    max_lengthscale: 100.
NS:
  method: 'jaxns'
  jaxns:
    dlogz_goal: 0.1
    max_call: 1e5
    difficult_model: True
    final_ns_dlogz: 0.01
    parameter_estimation: True
  dynesty:
    dlogz_goal: 0.1
    max_call: 1e5
    final_ns_dlogz: 0.01
    dynamic: False
     
ACQ:
  method: WIPV
  WIPV:
    num_samples: 512
    warmup_steps: 512
    thinning: 8
    batch_size: 1
optimizer:
  method: optax
  optax: 
    steps: 100
    start_learning_rate: 1e-2
    n_restarts: 4
    jump_sdev: 0.1
